//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAssistant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_transaction
    {
        public int id { get; set; }
        public int printer_id { get; set; }
        public string cartridge { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string vender { get; set; }
        public string in_out { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual printer printer { get; set; }
    }
}
