//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAssistant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class contact
    {
        public int id { get; set; }

        public string department { get; set; }

        public string name { get; set; }

        public string tel_office { get; set; }

        public string tel_ext { get; set; }

        public string tel_mobile { get; set; }

        public string note { get; set; }
    }
}
