//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAssistant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mis_assistantEntities : DbContext
    {
        public mis_assistantEntities()
            : base("name=mis_assistantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<vender> vender { get; set; }
        public virtual DbSet<cart_transaction> cart_transaction { get; set; }
        public virtual DbSet<printer> printer { get; set; }
    }
}
